project:
  type: website

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

website:
  twitter-card: false
  open-graph: true
  repo-actions: [issue]
  navbar:
    background: primary
    search: true
    right: 
      - icon: github
        href: "https://github.com/fligt/nbsqueeze"
  sidebar:
    style: floating

metadata-files: [nbdev.yml, sidebar.yml]
