# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/nbsqueeze',
                'doc_host': 'https://fligt.github.io',
                'git_url': 'https://github.com/fligt/nbsqueeze',
                'lib_path': 'nbsqueeze'},
  'syms': {'nbsqueeze.core': {'nbsqueeze.core.foo': ('core.html#foo', 'nbsqueeze/core.py')}}}
