# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/nbsqueeze',
                'doc_host': 'https://fligt.github.io',
                'git_url': 'https://github.com/fligt/nbsqueeze',
                'lib_path': 'nbsqueeze'},
  'syms': { 'nbsqueeze.squeeze': { 'nbsqueeze.squeeze.clean_imdir': ('extract.html#clean_imdir', 'nbsqueeze/squeeze.py'),
                                   'nbsqueeze.squeeze.export_pngs': ('extract.html#export_pngs', 'nbsqueeze/squeeze.py'),
                                   'nbsqueeze.squeeze.find_links': ('extract.html#find_links', 'nbsqueeze/squeeze.py'),
                                   'nbsqueeze.squeeze.find_png_strings': ('extract.html#find_png_strings', 'nbsqueeze/squeeze.py'),
                                   'nbsqueeze.squeeze.make_imdir': ('extract.html#make_imdir', 'nbsqueeze/squeeze.py'),
                                   'nbsqueeze.squeeze.replace_strings': ('extract.html#replace_strings', 'nbsqueeze/squeeze.py'),
                                   'nbsqueeze.squeeze.squeeze': ('extract.html#squeeze', 'nbsqueeze/squeeze.py'),
                                   'nbsqueeze.squeeze.squeeze_this_nb': ('extract.html#squeeze_this_nb', 'nbsqueeze/squeeze.py')}}}
